### ISSUE TITLE
use SQLAlchemy for DB access

### ISSUE THREAD

**Issue by nesnoj** [openego/dingo#10]
Is required since @MGlauer uses SQLAlchemy for the interface to oedb.
We need [GeoAlchemy](http://geoalchemy-2.readthedocs.io/en/0.2.6/index.html) for PostGIS types & operations.

**Comment by nesnoj** [comment]
I added SQLAlchemy table definitions for import & export in 0451178.

Next step: Change import methods in [NetworkDingo](https://github.com/openego/dingo/blob/dev/dingo/core/__init__.py#L13). Since there are no operations allowed in the table definitions mentioned above, the calculations and joins within the old SQL statement have to be replaced by SQLAlchemy operations..

Question: Since we gonna use the new SQLAlchemy format for DB-interface description, there's no need for the [config_db_tables](https://github.com/openego/dingo/blob/dev/dingo/config/config_db_tables) anymore, right?

**Comment by gplssm** [comment]
Finished by 19fb0b78737834b1245cf5e69ce26ba2275c7b46
