### ISSUE TITLE
LV trafo types for very small LV grid districts

### ISSUE THREAD

**Issue by nesnoj** [openego/dingo#103]
The smallest LV trafo is 100 kVA - way too large for very small LV grid districts. We may introduce 30 and 50 kVA types (definition is done in [equipment-parameters_LV_transformers.csv](https://github.com/openego/dingo/blob/dev/dingo/data/equipment-parameters_LV_transformers.csv))

**Comment by nesnoj** [comment]
Couldn't find sources with R+X - may get from Sincal..

**Comment by nesnoj** [comment]
I added a 50 kVA type using @jochenbuehler's method in 376a2170cb696174f1d1d319a6b9b1ef34ce32d2:
`R = u_Rr/100% * U_US^2/S` and `X = u_kr/100% * U_US^2/S` using u_Rr=2.45 and u_kr=6.15

**Comment by gplssm** [comment]
:rocket:

**Comment by jochenbuehler** [comment]
We just shouldnt Forget to mention in the final report that the data of the 50kVA transformer is not includet in the data of our source (Torsten Werth; Netzberechnung mit Erzeugungsprofilen)
