### ISSUE TITLE
isolated LV load areas 

### ISSUE THREAD

**Issue by nesnoj** [openego/dingo#108]
Some LV load areas got no grid although they contain ONS and centre point - example (mvgd id=480, lvla id=63250):

![mv_grid_ont_bug](https://cloud.githubusercontent.com/assets/15910173/21883594/37c9b708-d8b0-11e6-8ac1-2c0f0f94e9f6.png)

(green point is RES)

**Comment by nesnoj** [comment]
There's no entry for lvla id=63250 in the peak load table - currently the table calc_ego_loads.calc_ego_peak_load is used but may be outdated?
Is the calculation of peak loads part of data proc?

**Comment by Ludee** [comment]
Yesm [peak_load_per_load_area.py](https://github.com/openego/data_processing/blob/master/dataprocessing/python_scripts/peak_load_per_load_area.py) is part of eGoDP.
@gplssm is author. Will have a look
