### ISSUE TITLE
max. voltage drop / overvoltage in LV+MV grid

### ISSUE THREAD

**Issue by nesnoj** [openego/dingo#134]
In the SciGRID paper a voltage level of 104% * U_N and max. voltage drop / overvoltage of 4% is used. This results in a max. voltage drop / overvoltage of 2% in LV part (MV-LV substation and LV grid) which is unrealistic. Use 104% and 2% for future runs.
(DSO use 102.5% ± 1.5% => 104% in worst case)

**Comment by nesnoj** [comment]
Also, max. voltage drop is to be respected [during ring creation](https://github.com/openego/dingo/blob/751efc1e3607073e2b146d717e53d79dfedcde46/dingo/grid/mv_grid/models/models.py#L204).

**Comment by nesnoj** [comment]
We gotta talk about this one again @gplssm @jochenbuehler

**Comment by nesnoj** [comment]
Todos:
- [ ] Use separate U (U_N?) and delta_U for load case (ring creation) and feedin case (reinforcement)
- [ ] Reinforcement: Use U_N instead of U

**Comment by gplssm** [comment]
I go for a run on the server
