### ISSUE TITLE
Consider `apartment_house_branch_ratio` when chosing LV grid topology

### ISSUE THREAD

**Issue by gplssm** [openego/dingo#137]
This parameter is currently neglected, see [TODO](https://github.com/openego/dingo/commit/7797a105508fcfd93498881f722cf186b3a81366#L729-#L730)

**Comment by gplssm** [comment]
Should be resolved by 244c3e0e3d3e2ec725b670247aaf346ef645964c but is not tested

**Comment by nesnoj** [comment]
@gplssm: The parameter `apartment_house_branch_ratio` was already implicitly considered in your csv - so with the commit it was considered twice, which lead to #151.
