### ISSUE TITLE
choice of LV grid if population=0

### ISSUE THREAD

**Issue by nesnoj** [openego/dingo#147]
Addendum to #127: If there is no population given, we are to decide what kind of grid we use.
Proposal: In febd58dde4c90117f0169c438620f3e6e02984a0 a station and grid is created even if there's no population. We add branch lines as described in #127.
Please code [here](https://github.com/openego/dingo/blob/febd58dde4c90117f0169c438620f3e6e02984a0/dingo/core/__init__.py#L231).

**Comment by nesnoj** [comment]
please consider load factor `load_factor_lv_trans_lc_normal` from config_calc instead of implicitly assuming 100%. (update docstring too)

**Comment by gplssm** [comment]
Transformator LF is now considered (see 93c8a65912bc9250c628cea55e08166f14ba4253)

**Comment by gplssm** [comment]
There are to cases of population == 0:

 a) peak_load_residential == 0: no residential branches are created
 b) peak_load_residential > 0: no residential branches are created, identified peak_load is neglected in the following

We need a solution for that!

**Comment by nesnoj** [comment]
1. There're 105836 LVGD with zensus > 0 and residential peak load of 0:
2. There're 0 LVGD with zenus=0 and res. peak load > 0

snippet for 1:
```
SELECT count(id)
  FROM model_draft.ego_grid_lv_griddistrict
  WHERE zensus_sum>0 AND
  sector_peakload_residential = 0;
```

Another problem: Checking
```
SELECT count(id), sector_peakload_residential / zensus_sum AS x
  FROM model_draft.ego_grid_lv_griddistrict
  WHERE zensus_sum>0
  GROUP BY x;
```
u can notice that the peak load per inhabitant shows a wide - implausible - range!

**Comment by Ludee** [comment]
> @Ludee, where do you calculate sectoral consumption for LVGD? Couldn't find that in the LV scripts..

Sectoral consumption for LVGD are calculated in **ego_dp_lv_consumption_peakload.sql** written by @gplssm

**Comment by gplssm** [comment]
Population == 0 is actually handled in [build_residential_branches(lvgd)](https://github.com/openego/dingo/blob/52d12c84d2bd5a491edcbd6dfdc08ff6c545f68a/dingo/grid/lv_grid/build_grid.py#L625)

**Comment by gplssm** [comment]
There are 356275 distinct values for peak load per capita in LV grid districts
There are 356288 distinct values for consumption per capita in LV grid districts
There are 52 distinct values for peak load per capita in load areas

Whereas the 52 distinct values in the load areas are actually just 16 different values, hence the different values for the Bundesländer. The has to be found in the script that breaks down peak load from load areas to LV grid districts.

**Comment by gplssm** [comment]
There are 356275 distinct values for peak load per capita in LV grid districts
There are 356288 distinct values for consumption per capita in LV grid districts
There are 52 distinct values for peak load per capita in load areas

Whereas the 52 distinct values in the load areas are actually just 16 different values, hence the different values for the Bundesländer. The has to be found in the script that breaks down peak load from load areas to LV grid districts.

**Comment by gplssm** [comment]
The actual issue was that residential peak load (consumption) was scaled by area instead of by population. This is changed in 18f6da1038a802311805d1ccaac069ac9dc72b3a

In addition 85fda0aa1723ee7968398891b748531d43cf4943  includes a change in calculation of consumption in LVGDs for other sectors.
Breaking sectoral consumption  was achieved by scaling sectoral consumption of LA by the fraction of sectoral area. But, due to superposition of sectoral land-use areas (even from the same sector), the result was maybe erroneous. 
Now scaling is done by dividing the sectoral land-use area in each LVGD by the sum of sectoral land-use area in the associated LA.

**Comment by gplssm** [comment]
Re-running `ego_dp_lv_consumption_peakload.sql` didn't solved the peak load issue for residential sector.

**Comment by nesnoj** [comment]
So y is this one closed then?

**Comment by gplssm** [comment]
I fixed a last issue and now dataset seems to valid - at least way more reliable. 

1. Now 296 different values of peak_load per capita exist (instead 350+k).
2. These range between 4.55171747983083e-08 GW/(capita * a) and 6.61506396678214e-07 GW/(capita * a)
3. 4 LVGDs exist with population and peak_load = 0

**Comment by nesnoj** [comment]
Well done!
But is a peak load of 45.5 W realistic?

**Comment by gplssm** [comment]
True, 45.5 W/capita as peak load seems to quite low. But, if we scale this up by total population of roughly 80M people in Germany a cumulative peak load of 36.4 GW results. This is only the fraction of the peak load from the household sector. Thus, the household sector has a share of ~42% on the cumulative peak load. This seems to be fair for me.

**Comment by nesnoj** [comment]
My calculator, at least, states 45.5W * 8*10^7 / 10^9 = 3.64GW

**Comment by gplssm** [comment]
Mine too (if I take 8*10^7 instead of 80*10^7)! So... damn!

But... This was just the lower boundary of peak load. The upper boundary (661 W/capita) refers to a cumulative peak load in the household sector of 52.88 GW.

This calls for a calculation based on the average peak load per capita and a histogram ;-)

**Comment by nesnoj** [comment]
Your average fits well the cum. peak load of `28.3 GW` using
```
SELECT sum(sector_peakload_residential)
FROM demand.ego_dp_loadarea
WHERE version='v0.2.10';
```
Seems quite plausible..

**Comment by gplssm** [comment]
:smile:
