### ISSUE TITLE
Discussion: max. load per branch line

### ISSUE THREAD

**Issue by gplssm** [openego/dingo#160]
I changed max. load per branch line to 290 kVA. Doing this, the largest cable can transport this load.

@nesnoj what do you think of this? If you don't like it, just revert 46581e4c5eab5401c45940cd2eb0784a3da2d3a8

**Comment by nesnoj** [comment]
Sound reasonable, I added a comment in config_calc 41e1e2b7232969a20d1b2a98342aa20de65ed85d.
