### ISSUE TITLE
Correlation between population and peak_load_residential is maybe missing

### ISSUE THREAD

**Issue by gplssm** [openego/dingo#161]
Check correlation of both parameters on exemplary LV grid districts

**Comment by nesnoj** [comment]
see #147 for current status

**Comment by gplssm** [comment]
Fixed in ego.dataprocessing

**Comment by nesnoj** [comment]
@gplssm Is this one _probably-fixed_, _tested_ or has there been already a _re-run_ of dp?

**Comment by gplssm** [comment]
Sorry, my confused mind let me close this one...

**Comment by nesnoj** [comment]
We could close this one and add it to #169
