### ISSUE TITLE
NetworkDingo has two equivalent mv_grid_districts

### ISSUE THREAD

**Issue by gplssm** [openego/dingo#165]
Is it a bug or a hidden feature? I don't get it
![dingo_two_mvgds](https://cloud.githubusercontent.com/assets/8255114/25846388/e991fac4-34b1-11e7-8ab1-2e7ff5a55e19.png)

**Comment by nesnoj** [comment]
Reason was the versioning combined with the table join => result were two identical datasets.
Solution: Use of `SELECT DISTINCT`
Beware in future usages of joins.
