### ISSUE TITLE
create logo

### ISSUE THREAD

**Issue by nesnoj** [openego/dingo#166]
oh yea! I will do this on Friday..

**Comment by gplssm** [comment]
:+1:

Am 10.05.2017 11:30 nachm. schrieb nesnoj <notifications@github.com>:

oh yea! I will do this on Friday..

-

**Comment by nesnoj** [comment]
Some drafts, please gimme a vote @gplssm @EdithaK @Ludee @jochenbuehler 

**LOGO A1**
![reduced-dingo_logo8](https://cloud.githubusercontent.com/assets/15910173/26524933/fef26b26-4346-11e7-916e-ee1dd98a668c.png)
___
**LOGO A2**
![reduced-dingo_logo11](https://cloud.githubusercontent.com/assets/15910173/26524937/0f0f281e-4347-11e7-8f73-f97eb364c483.png)
___
**LOGO A3**
![reduced-dingo_logo12](https://cloud.githubusercontent.com/assets/15910173/26524938/16ed2798-4347-11e7-9678-1ff2ee0c6635.png)
___
**LOGO A4**
![reduced-dingo_logo13](https://cloud.githubusercontent.com/assets/15910173/26524941/23ef8742-4347-11e7-8982-89c0e4aef8f9.png)
___
**LOGO A5**
![reduced-dingo_logo14](https://cloud.githubusercontent.com/assets/15910173/26524943/2a1af836-4347-11e7-9c64-a2e564353096.png)
___
**LOGO B1 (mr. psychodingo)**
![reduced-dingo_logo9](https://cloud.githubusercontent.com/assets/15910173/26524946/3f5b6d3e-4347-11e7-96ac-30b4d0e25d2a.png)
___
**LOGO C1 (o'reilly sytle)**
![reduced-dingo_logo10](https://cloud.githubusercontent.com/assets/15910173/26524952/548fc6aa-4347-11e7-8b2a-5ecf414ba741.png)
___
**LOGO D1**
![reduced-dingo_logo15](https://cloud.githubusercontent.com/assets/15910173/26524960/72c4f3ac-4347-11e7-994d-bdd7585f0bc0.png)
___
**LOGO E1**
![reduced-dingo_logo16](https://cloud.githubusercontent.com/assets/15910173/26524961/7cbca5d0-4347-11e7-8a1a-c54e8630b0f5.png)
___
**LOGO F1**
![reduced-dingo_logo4](https://cloud.githubusercontent.com/assets/15910173/26524973/f02e01da-4347-11e7-897f-8d0b89a1deea.png)
___
**LOGO G1**
![reduced-dingo_logo17](https://cloud.githubusercontent.com/assets/15910173/26525033/b63c1866-4349-11e7-8da8-9fc30aa8cb0c.png)

**Comment by nesnoj** [comment]
Edit: Or add another version :)

**Comment by gplssm** [comment]
I'm impressed! I think there is not need to make additional proposals...

My top three are (descending by preference)
C1
E1
A5

**Comment by jochenbuehler** [comment]
A5

**Comment by EdithaK** [comment]
A3 G1

**Comment by EdithaK** [comment]
Stimmt, A5 ist auch gut.

**Comment by Ludee** [comment]
Veto on A3 & A5 because of icon in the text! Don't mix.
The animial is a good idea but perhaps only an "insider".

G1 is simple and good.
F1 is favourite because of similarities with the open_eGo logo!
Mix of G1 & F1 would be perfect and match with eGo.

**Comment by nesnoj** [comment]
Ok, let's go for **A5**
![reduced-dingo_logo14](https://cloud.githubusercontent.com/assets/15910173/26832184/f42aefd0-4ace-11e7-9a1a-26c28f4b450a.png)
Thank you for voting!

U can find the logo in project folder.
