### ISSUE TITLE
Statistical analysis of Dingo grid topology data

### ISSUE THREAD

**Issue by gplssm** [openego/dingo#178]
There are several motivations for performing a statistical evaluation of Dingo grid topology data.

1. Evaluate results of recents features addtition (see #169 )
2. Assess quality of input data: for example data on location of RES generators can be evaluated by analysing grid connection points
3. Provide potential users on  overview on available data

**Comment by nesnoj** [comment]
Please consider #186, #122

**Comment by gplssm** [comment]
Implementation of calculating key figures is separated into two steps: one for MV (#189) another for LV (#190).

**Comment by gplssm** [comment]
**List of statistical evalutation aspects** _(to be extended)_

1. Are voltage levels at nodes exceeding limits?
2. Are branches overloaded?

**Comment by gplssm** [comment]
Closed in favor of #212
