### ISSUE TITLE
Sensitive data in git/GitHub

### ISSUE THREAD

**Issue by MGlauer** [openego/dingo#2]
Keep in mind, that you must not commit any sensitive data to git/GitHub. Git saves each file in its history. Rewriting the history is not a trivial task and changes all commit ids. 

Instead: Move critical data (e.g. database login etc) to a separate file (e.g. security.py) and add this name to the .gitignore. 

In order to simplify the usage of this concept you could commit a file "security.py.default" with invalid logins (e.g. user="user" etc.) that can be adapted as needed by every user.

**Comment by gplssm** [comment]
Thanks for the hint, we'll consider it!
