### ISSUE TITLE
MV grid max. distance outliers

### ISSUE THREAD

**Issue by nesnoj** [openego/dingo#201]
We have different grids with quite long total length from HV-MV subst. to farthest MV-LV subst. (ring(s) are open) with a max. of ~84km (MVGD 3093). We might add an additional constraint on max. half-ring length in `tech_constraints_satisfied()`.
To evaluate the need, a histogram of max. distances should be created first (see #189).

**Comment by nesnoj** [comment]
This example was caused by the circ. breaker relocation using loads as well as generators.
From 1046681149ba9358056df97cd684572cc7ce8070 (see also #167) on the standard value is loads only, so this MVGD should be ok now.
@gplssm Please create a new grid dataset as soon as I give you a go (I wanna fix sth else first)

**Comment by gplssm** [comment]
Yep, I'll do that. I did a new run on the weekend and it took only 24 hrs...

**Comment by nesnoj** [comment]
:ok:, this one is done too. U can go for it

**Comment by nesnoj** [comment]
Update - what I did:
I added an additional constraint for the max. ring length of `2 * v_level * max_ring_length_factor` (e.g. in a 20kV grid assuming max_ring_length_factor=1.5 (default in `config_calc`) the max ring length would be 60km) . `max_ring_length_factor` is used to achieve more variance in the grids.

@jochenbuehler Is a factor of 1.5 reasonable?

**Comment by jochenbuehler** [comment]
Seems so:
![unbenannt](https://user-images.githubusercontent.com/28706452/28621831-8b412604-7212-11e7-8a1d-f9d3545ac5c2.png)

**Comment by nesnoj** [comment]
See #224 for new implementation
