### ISSUE TITLE
unstable MV grids: Get and store info

### ISSUE THREAD

**Issue by nesnoj** [openego/dingo#206]
There's no way to notice whether a created MV grid is stable or not (some voltage/current issues could not be resolved) except by reading the log (line is written [here](https://github.com/openego/dingo/blob/ee237e37d4c228081e1e246d7e6d0d431c6dda9e/dingo/flexopt/reinforce_grid.py#L81)). We need a conspicuous warning and a flag in MVGridDistrictDingo, a list of unstable grids in NetworkDingo or similar!
Additionally, we could add an additional parameter/option (e.g. `stable_only`) to the pickle export method to control if only stable grids are accepted..
@gplssm What do u think?

**Comment by gplssm** [comment]
Sounds like a nice feature!

My plan was actually to do this via the statistical analysis: export the number of unstable nodes/lines in a grid or similar.

**Comment by gplssm** [comment]
Closed in favor of #212
