### ISSUE TITLE
Shared attributes

### ISSUE THREAD

**Issue by MGlauer** [openego/dingo#3]
There is a number of classes that share several attributes e.g. in dingo.core.network BranchDingo and TransformerDingo:
```
self.equip_trans_id = kwargs.get('equip_trans_id', None)
self.v_level = kwargs.get('v_level', None)
self.s_max_a = kwargs.get('s_max_a', None)
self.s_max_b = kwargs.get('s_max_b', None)
self.s_max_c = kwargs.get('s_max_c', None)
```

It might be better to create an additional class for these attributes and desing BranchDingo and TransformerDingo as subclasses. 

[Rule #3 - Never Write the Same Code Twice](http://www.cambiaresearch.com/articles/77/rule-3---never-write-the-same-code-twice)

**Comment by nesnoj** [comment]
I'm aware of this, currently the attributes are just placeholders..
Thank's for reviewing code:)
