### ISSUE TITLE
Move SQLalchemy object definitions to ego.io

### ISSUE THREAD

**Issue by gplssm** [openego/dingo#35]
Move object defined in https://github.com/openego/dingo/blob/c326390c3f32bb4a04b3433468a5b1eedcb37ddb/dingo/config/config_db_interfaces.py#L10-L78

Align them with @MGlauer definitions.

**Comment by gplssm** [comment]
All of the mentioned table objects are already defined in ego.io. Thanks to @MGlauer!

@nesnoj can I just delete them in Dingo?

**Comment by nesnoj** [comment]
yupp, kick it!

**Comment by gplssm** [comment]
Kicked by 20b967bf37444e474b86a6dd183cdfdedc98504c
