### ISSUE TITLE
Table select via 'config_db_tables'

### ISSUE THREAD

**Issue by gplssm** [openego/dingo#36]
Before using SQLAlchemy tables for Dingo data input where chosen by definitions in `config_db_tables` file. With SQLAlchemy this is done by importing the SQLAlchemy Table definition object from ego.io.

**Comment by gplssm** [comment]
@nesnoj do see any chance to do this choice of tables via the config file? I.e. choosing between *_ta tables and the normal ones?

**Comment by nesnoj** [comment]
:+1:
