### ISSUE TITLE
Where is subst_id and mvregion id obtained from?

### ISSUE THREAD

**Issue by gplssm** [openego/dingo#4]
...and should them be the same?

As motivation see the following result of dingo. The chosen mv_region is 217. 
![mv_grid_217](https://cloud.githubusercontent.com/assets/8255114/14989223/138c6dd4-1157-11e6-81ff-f4231ddfe8f9.png)

**Comment by nesnoj** [comment]
2 different ids for the MV regions were used: one for the regions and one for the substations. It's still the same but the region id was deleted in another table and new ids generated at the same time. Works now.
ToDo: I strongly recommend to define an id system that is long term stable..
