### ISSUE TITLE
performance of config and csv reading operations

### ISSUE THREAD

**Issue by nesnoj** [openego/dingo#57]
In different parts of dingo, config values are accessed and CSV data read quite often. 

Examples (config values):
1. [Determining default branch type](https://github.com/openego/dingo/blob/adfd1698691c8609570906e82f3f45ad6ca9cb6d/dingo/core/network/grids.py#L207)
2. [Checking tech. constraints](https://github.com/openego/dingo/blob/adfd1698691c8609570906e82f3f45ad6ca9cb6d/dingo/grid/mv_grid/models/models.py#L235-L245)

Examples (CSV reading):
1. [Determining default branch type](https://github.com/openego/dingo/blob/adfd1698691c8609570906e82f3f45ad6ca9cb6d/dingo/core/network/grids.py#L216)

We have to check the impact on overall performance. If it's too poor, we have to store it in a different way (and pass it to the corresponding method).

**Comment by gplssm** [comment]
Work on it, if required for this step. Otherwise, move it to milestone:"Nice-to-have addons"
