### ISSUE TITLE
add filter to sql queries when leaving test area

### ISSUE THREAD

**Issue by nesnoj** [openego/dingo#63]
In some queries in network's [init](https://github.com/openego/dingo/blob/dev/dingo/core/__init__.py) SQLAlchemy's `.filter` is not used (probably because the test area tables are used so it's not necessary). Due to bad performance it has to be added later!

Example: [`import_lv_grid_districts()`](https://github.com/openego/dingo/blob/a11bcfc4c965c7e6aff94e4473540bfffb6eafc7/dingo/core/__init__.py#L420)

**Comment by gplssm** [comment]
Is solved within "export2PyPSA"-Branch
