### ISSUE TITLE
Not-connected nodes in graph of MV grid

### ISSUE THREAD

**Issue by gplssm** [openego/dingo#68]
There exist nodes that are not connected to others in the graph even if `lv_load_area` is connected to the grid.
When exporting the grid like this, several subgraphs in the resulting power flow problem exist that lead to errors.

As interim solution, nodes that have no connection to neighboring nodes are excluded from the export. Done in 0088e44792c58d0ce258c7e9dbe654cd1f97e08b

**Comment by nesnoj** [comment]
This is related to #49 and will be treated there..
