### ISSUE TITLE
choice of transformers

### ISSUE THREAD

**Issue by nesnoj** [openego/dingo#7]
In method[ MVStationDingo.choose_transformers](https://github.com/openego/dingo/blob/dev/dingo/core/network/stations.py#L19-L86), an apparent_power of 39999 kW leads to 2 transformers with 40 MW each (1 regular and 1 redundant), so the load factor (e.g. 0.6) stays disregarded.

**Comment by gplssm** [comment]
Thanks for digging into that. I'll fix it! ;)

**Comment by gplssm** [comment]
Fixed by f5c14270724e2e3f47411d09309e59d1d5fb3678.
