### ISSUE TITLE
Attach aggregated LV generators to MV/LV substations

### ISSUE THREAD

**Issue by gplssm** [openego/dingo#72]

**Comment by nesnoj** [comment]
done.
currently LV genos were temporarily distributed equally to LVGD, see [here](https://github.com/openego/dingo/blob/8a01dc0fc542729f8236395ccbcb8cfe8dd79899/dingo/core/__init__.py#L781).
The proper allocation to LVGD can be done as soon as genos's "mvlv_subst_id" is correct.
