### ISSUE TITLE
Replace dummy LV grid districts by "real" ones

### ISSUE THREAD

**Issue by gplssm** [openego/dingo#74]
When @jong42 finished work on [LV grid districts script](https://github.com/openego/data_processing/blob/64c13970b501f6fa48e6a7bb609ce7c12f8f3fc6/dataprocessing/sql_snippets/process_eGo_lv_grid_districts.sql) and data thereof is generated, revert commit aa1977b7557202bba97a5af5539cde8812a46505.

The revert results in reading of actual lv grid district data from oedb.

**Comment by nesnoj** [comment]
Can be done when #93 is finished.

**Comment by nesnoj** [comment]
The first version of the new LVGD dataset is used with id, geom, allocation to substation (without population, demand, peak load) bd122da83bef55be7b14699976c9fdda15a4e09d
