### ISSUE TITLE
Open CircuitBreaker in all mv grids

### ISSUE THREAD

**Issue by gplssm** [openego/dingo#75]
Circuit breaker aren't always open as illustrated below for the example of mv grid 386. Make sure that circuit breakers are always opened when grid is exported.

![close_circuit_breaker_in_mvgrid_386](https://cloud.githubusercontent.com/assets/8255114/20346660/98eaf4c8-abfd-11e6-80ac-58fb66f7f2da.png)

**Comment by nesnoj** [comment]
Already done.
I pimped it up implementing a control function in NetworkDingo class in 3ae4adf3791a6cd2abe6bdfa20ac5125231464fe.
