### ISSUE TITLE
grid structure is meshed

### ISSUE THREAD

**Issue by nesnoj** [openego/dingo#83]
Some grids are meshed but they are not supposed to.
Example:
![mv_grid_mesh_bug](https://cloud.githubusercontent.com/assets/15910173/20926267/b81a4222-bbbb-11e6-9d95-d020796b4960.png)
I guess this structure is built accidentally during connection of generators. So maybe there's an additional check needed to avoid these structures..

**Comment by gplssm** [comment]
This is maybe partially related to not-opened circuit breakers, see #75 

Prior to fix this, check if all circuit breakers are opened.

**Comment by nesnoj** [comment]
couldn't reproduce, seems to be solved during mv_connect* measures..
