### ISSUE TITLE
parametrization of line/cables

### ISSUE THREAD

**Issue by nesnoj** [openego/dingo#9]
2 comments on MVGridDingo class' method [parametrize_lines](https://github.com/openego/dingo/blob/dev/dingo/core/network/grids.py#L99):

1. You do the parametrization after the routing but line specs are required to [check technical constraints](https://github.com/openego/dingo/blob/dev/dingo/grid/mv_routing/models/models.py#L172) during routing process - let's discuss this topic again..?
2. For iteration of the graph's edges ([used here](https://github.com/openego/dingo/blob/dev/dingo/core/network/grids.py#L167)), you can use the generator method [GridDingo.graph_edges()](https://github.com/openego/dingo/blob/dev/dingo/core/network/__init__.py#L64)

**Comment by nesnoj** [comment]
I'll move the method to the tech. constraints

**Comment by gplssm** [comment]
Point (1) is solved by moving and adapting parametrize_lines().

**Comment by nesnoj** [comment]
Done
