### ISSUE TITLE
use DataFrames instead of database to interface pypsa

### ISSUE THREAD

**Issue by nesnoj** [openego/dingo#91]
Profiling reveals that the export of MV grid to db tables for pypsa actually takes some time:

![dingo_profile1](https://cloud.githubusercontent.com/assets/15910173/21051342/2160315e-be20-11e6-8224-e8a84ebf46ea.png)
We better go for pandas DataFrames to pass the data to pypsa.
We keep the database structure as possibility for exchanging grids.

**Comment by gplssm** [comment]
Indeed!

I would suggest to take (and maybe adopt) current database structure for grid to export the final result.

**Comment by gplssm** [comment]
See progress in #92

Still pending tasks
- [ ] pq_set and v_mag_set via DataFrame
- [ ] `run_powerflow()` based on DataFrames

**Comment by gplssm** [comment]
Done. Discovered issues with new spicy salt that gets involved when generators are connected. See over here #98 

Performance
 - via DataFrames: ~16s (new)
 - via database: ~46s (before)
